kind: Service
apiVersion: v1
metadata:
  name: gsp-console-service
spec:
  type: LoadBalancer
  selector:
    app: gsp-console
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30300
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gsp-console 
  labels:
    app: gsp-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gsp-console
  template:
    metadata:
      labels:
        app: gsp-console
        version: "1.0.4"
    spec:
      containers:
      - name: gsp-console
        image: docker.gsp.sicc.co.kr/console:1.0.4
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prd
        - name: spring.cloud.config.uri
          value: http://100.102.123.211:8888
        ports:
        - name: http
          containerPort: 8080
